### ISSUE TITLE
npm run deploy isn't working

### ISSUE THREAD

**Issue by almet** [spiral-project/formbuilder#26]
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error
>     at new JS_Parse_Error (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)
>     at js_error (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)
>     at croak (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:663:9)
>     at token_error (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:671:9)
>     at unexpected (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:677:9)
>     at expr_atom (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1161:13)
>     at maybe_unary (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1334:19)
>     at expr_ops (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1369:24)
>     at maybe_conditional (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1374:20)
>     at maybe_assign (/home/alexis/dev/github.com/formbuilder/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1398:20)

**Comment by almet** [comment]
https://github.com/spiral-project/formbuilder/pull/28
